# RS485
# GPIO1 - RS485_TX
# GPIO3 - RS485_RX
# GPIO13 - flow control

substitutions:
  rx_pin: GPIO3
  tx_pin: GPIO1
  flow_control_pin: GPIO13
  slave_1: N4IOA01


esphome:
  name: esp32-n4ioa01
  friendly_name: esp32_n4ioa01

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: debug
  baud_rate : 0 # disable hardware output

# Enable Home Assistant API
api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

uart:
  id: mod_bus
  rx_pin: ${rx_pin}
  tx_pin: ${tx_pin}
  baud_rate: 9600
  stop_bits: 1
  parity: NONE
  data_bits: 8
  debug:
    direction: BOTH

modbus:
  id: modbus1
  flow_control_pin: ${flow_control_pin} #for use when you use a rs485 board without auto flow control. Like the rs485 max board.

modbus_controller:
  - id: ${slave_1}
    address: 0x1
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 5sec

number:
  - platform: modbus_controller
    modbus_controller_id: ${slave_1}
    id: ${slave_1}_write_current_value
    name: "${slave_1} set current"
    address: 0x00
    unit_of_measurement: "mA"
    min_value: 4
    max_value: 20
    step: 0.5
    multiply: 100
    value_type: U_WORD

sensor:
# Current Modul
  - platform: modbus_controller
    modbus_controller_id: ${slave_1}
    name: "${slave_1} current value"
    id: ${slave_1}_read_current_value
    register_type: holding
    address: 0x0000
    unit_of_measurement: "mA"
    state_class: "measurement"
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    value_type: U_WORD

# Current Modul
  - platform: modbus_controller
    modbus_controller_id: ${slave_1}
    name: "${slave_1} current ratio"
    id: ${slave_1}_read_current_ratio
    register_type: holding
    address: 0x0007
    unit_of_measurement: "%"
    state_class: "measurement"
    accuracy_decimals: 2
    filters:
      - multiply: 0.1
    value_type: U_WORD

